name: nightly tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment to run tests in'
        required: true
        default: 'dev'
        type: choice
        options: [dev, qa, prod]



jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      set-env: ${{ steps.set-env.outputs.env }}
    steps:
      - name: Set environment variable
        id: set-env
        run: |
          if [[ "${{ github.event.inputs.Environment }}" == "dev" ]]; then
            echo "env=development" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.Environment }}" == "qa" ]]; then
            echo "env=quality-assurance" >> $GITHUB_OUTPUT
          else
            echo "env=production" >> $GITHUB_OUTPUT
          fi

          echo $set-env

  test:
    runs-on: ubuntu-latest
    needs: pre
    environment: ${{ needs.pre.outputs.set-env }}
    steps:
      - name: Running tests
        run: |
          echo "Running tests in environment: ${{ needs.pre.outputs.set-env }}"
          echo "Job environment: ${{ env }}"
          echo "GitHub environment: $GITHUB_ENV"

