name: Run python tests

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set-up python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        
      - name: Run tests with pytest
        run: |
          echo "====== Start running tests ======"
          pytest -v
          echo "===== Finish running tests ======"

      
